-- liquibase formatted sql

-- changeset jrembo:1

CREATE TABLE users
(
    id        BIGINT generated by default as identity primary key,
    user_id   BIGINT NOT NULL,
    nick_name TEXT   NOT NULL

);