-- liquibase formatted sql

-- changeset aleksey:1
CREATE TABLE users
(
    id            BIGINT generated by default as identity primary key,
    telegram_id   BIGINT   NOT NULL,
    telegram_nick TEXT,
    first_name    TEXT,
    last_name     TEXT,
    phone_number  TEXT,
    car_number    TEXT,
    email         TEXT,
    address       TEXT,
    shelter_type  SMALLINT,-- enum ShelterType
    user_type     SMALLINT NOT NULL,-- enum UserType
    user_status   SMALLINT NOT NULL -- enum UserStatus
);

CREATE TABLE animals
(
    id        BIGINT generated by default as identity primary key,
    nick_name TEXT     NOT NULL,
    pet_type  SMALLINT NOT NULL,-- enum PetType
    color     SMALLINT NOT NULL,-- enum Color
    sex       SMALLINT NOT NULL -- enum Sex
);

CREATE TABLE adopters
(
    id         BIGINT generated by default as identity primary key,
    user_id    BIGINT,
    animal_id  BIGINT NOT NULL,
    shelter_id BIGINT NOT NULL
);

CREATE TABLE shelters
(
    id                 BIGINT generated by default as identity primary key,
    address_shelter    TEXT     NOT NULL,
    time_work          TEXT     NOT NULL,
    driving_directions TEXT     NOT NULL,
    phone_shelter      TEXT     NOT NULL,
    phone_security     TEXT     NOT NULL,
    shelter_type       SMALLINT NOT NULL -- enum ShelterType
);

CREATE TABLE reports
(
    id                    BIGINT generated by default as identity primary key,
    user_id               BIGINT   NOT NULL,
    date_report           DATE     NOT NULL,
    status_report         SMALLINT NOT NULL, -- enum StatusReport
    date_end_of_probation DATE,
    link_picture          BYTEA,
    report_text           TEXT
);

CREATE TABLE dialogs
(
    id           BIGINT generated by default as identity primary key,
    guest_id     BIGINT NOT NULL,
    volunteer_id BIGINT,
    text_message TEXT   NOT NULL,
    date_message DATE   NOT NULL
);


